name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Mengaktifkan tombol menu "Run workflow" manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Membuat berkas rilis dan mengompres ukuran APK menjadi kecil
    - name: Build Release APK
      run: ./gradlew assembleRelease

    # Proses Menandatangani APK secara manual menggunakan SDK Android bawaan server
    - name: Sign APK Manual
      id: sign_app
      run: |
        # 1. Ambil file Keystore dari GitHub Secrets dan simpan di root direktori
        echo "${{ secrets.SIGNING_KEY }}" | base64 -d > $GITHUB_WORKSPACE/release.keystore
        
        # 2. Cari lokasi folder build-tools terbaru secara otomatis di server
        BUILD_TOOLS_DIR=$(ls -d $ANDROID_HOME/build-tools/* | sort -V | tail -n 1)
        echo "Menggunakan Build Tools dari: $BUILD_TOOLS_DIR"
        
        # 3. Tentukan path APK secara eksplisit dari root
        APK_DIR="$GITHUB_WORKSPACE/app/build/outputs/apk/release"
        
        # 4. Lakukan Zipalign (Optimasi ukuran berkas)
        $BUILD_TOOLS_DIR/zipalign -v 4 \
          $APK_DIR/app-release-unsigned.apk \
          $APK_DIR/app-release-aligned.apk
        
        # 5. Tanda tangani APK menggunakan apksigner resmi
        $BUILD_TOOLS_DIR/apksigner sign \
          --ks $GITHUB_WORKSPACE/release.keystore \
          --ks-key-alias "${{ secrets.ALIAS }}" \
          --ks-pass pass:"${{ secrets.KEY_STORE_PASSWORD }}" \
          --key-pass pass:"${{ secrets.KEY_PASSWORD }}" \
          --out $APK_DIR/app-release-signed.apk \
          $APK_DIR/app-release-aligned.apk
          
        # 6. Verifikasi hasil tanda tangan
        $BUILD_TOOLS_DIR/apksigner verify $APK_DIR/app-release-signed.apk
        
        # 7. (Opsional) Hapus file keystore demi keamanan runner
        rm $GITHUB_WORKSPACE/release.keystore
        
    # Mengunggah hasil APK rilis yang sudah kecil dan sukses ditandatangani
    - name: Upload Signed APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AndroidSystemKeyVerifier
        path: app/build/outputs/apk/release/app-release-signed.apk

